# Generated by Django 3.0.3 on 2020-02-07 11:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('houseNumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solarweekly', models.DecimalField(decimal_places=2, max_digits=7)),
                ('energyweelky', models.DecimalField(decimal_places=2, max_digits=7)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.HouseDetails')),
            ],
        ),
        migrations.CreateModel(
            name='RoomStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=50)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=7)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.HouseDetails')),
            ],
        ),
        migrations.CreateModel(
            name='RoomControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heating', models.SmallIntegerField()),
                ('light', models.SmallIntegerField()),
                ('window', models.BooleanField(default=False)),
                ('door', models.BooleanField(default=False)),
                ('safetyalarm', models.BooleanField(default=False)),
                ('roomID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.RoomStats')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.HouseDetails')),
            ],
        ),
        migrations.CreateModel(
            name='HouseStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solarproduction', models.DecimalField(decimal_places=2, max_digits=7)),
                ('batterycharge', models.DecimalField(decimal_places=2, max_digits=7)),
                ('energyconsumtion', models.DecimalField(decimal_places=2, max_digits=7)),
                ('moneysaved', models.DecimalField(decimal_places=2, max_digits=7)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.HouseDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('deviceconsumption', models.DecimalField(decimal_places=2, max_digits=7)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.RoomStats')),
            ],
        ),
    ]
